name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # see https://github.com/actions/setup-node
      - name: node setting
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: install redoc
        run: npm install -g @redocly/cli

      - name: build open api
        run: |
          redocly build-docs ./openapi.yaml
          mkdir ./public
          mv ./redoc-static.html ./public/index.html
  
      # see https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
